#############################################################################
##
##  GroupClassifier.g
##
##  Standard path: classification of Irr_{p'}(G) by explicitly computing
##  the groups involved (G, Aut, normalizers, A) and the action of the
##  outer automorphism on Irr(G).  Used when the library tables are not
##  enough for the Clifford shortcut.
##
##  General steps (when |Out| = 2):
##    1. Stabilizer Aut(G)_P of the p-Sylow in Aut(G).
##    2. Outer coset Aut(G)_P / Inn(G)_P (order 1 or 2).
##    3. If non-trivial: lift outer_gen and permutation sigma of classes.
##    4. Permutation sigma_Irr induced on Irr(G).
##    5. Classification: type 1 if chi^sigma_Irr = chi, type 2 otherwise.
##
##  Optional Clifford verification: builds A = G semidirect <outer_gen>
##  (with [A:G] = Order(outer_gen), not necessarily 2), its character
##  table and the class fusion; collects witnesses as in TableClassifier.
##
#############################################################################

#############################################################################
##
##  InnerAutomorphismsSubgroup( S_hat )
##
##  Returns the subgroup Inn(S_hat) <= Aut(S_hat), generated by conjugation
##  by each generator of S_hat.
##
#############################################################################
InnerAutomorphismsSubgroup := function(S_hat)
    return Group(
        List(GeneratorsOfGroup(S_hat), g -> InnerAutomorphism(S_hat, g))
    );;
end;;

#############################################################################
##
##  PermutationOfClassesByAutomorphism( G, alpha )
##
##  Permutation sigma on {1, ..., k} such that alpha sends the i-th class
##  to the sigma(i)-th class.  Returns a PermList.
##
#############################################################################
PermutationOfClassesByAutomorphism := function(G, alpha)
    local classes, images, i, image, position;;

    classes := ConjugacyClasses(G);;
    images := [];;

    ProgressMessage("Computing the permutation of classes under alpha.");;
    for i in [1 .. Length(classes)] do
        LoopProgress("Classes under alpha", i, Length(classes));;
        image := Image(alpha, Representative(classes[i]));;
        position := PositionProperty(classes, c -> image in c);;
        if position = fail then
            Error("Image of class ", i, " under alpha not found.");;
        fi;;
        Add(images, position);;
    od;;

    return PermList(images);;
end;;

#############################################################################
##
##  OuterActionOnIrr( G, table, outer_gen )
##
##  Permutation that outer_gen induces on Irr(table).  For each chi_i we
##  build chi_i^alpha (as a list of values) and look it up in Irr via a
##  String(values) -> index dictionary.
##
##  outer_gen = fail => trivial permutation (every Irr is alpha-invariant).
##
##  Returns rec(class_perm, char_perm).  Asserts that perm^2 = id.
##
#############################################################################
OuterActionOnIrr := function(G, table, outer_gen)
    local irr, num_classes, values, class_perm, index_by_values,
          images, i, vals, key, position, char_perm;;

    irr := Irr(table);;
    num_classes := NrConjugacyClasses(table);;

    if outer_gen = fail then
        return rec(class_perm := (), char_perm := ());;
    fi;;

    values := List(irr, chi -> ValuesOfClassFunction(chi));;
    class_perm := PermutationOfClassesByAutomorphism(G, outer_gen);;

    # Dictionary for amortized O(1) lookup.
    index_by_values := rec();;
    for i in [1 .. Length(values)] do
        index_by_values.(String(values[i])) := i;;
    od;;

    images := [];;
    ProgressMessage("Computing the outer action on Irr(G).");;
    for i in [1 .. Length(irr)] do
        LoopProgress("Outer image of Irr", i, Length(irr));;
        # chi^alpha(C_j) = chi(C_{sigma^{-1}(j)})
        vals := List(
            [1 .. num_classes],
            j -> values[i][j ^ (class_perm^-1)]
        );;
        key := String(vals);;
        if IsBound(index_by_values.(key)) then
            position := index_by_values.(key);;
        else
            Error("chi[", i, "]^alpha not found in Irr(G).");;
        fi;;
        Add(images, position);;
    od;;

    char_perm := PermList(images);;
    if char_perm^2 <> () then
        Error("The outer action on Irr does not have order 1 or 2.");;
    fi;;

    return rec(class_perm := class_perm, char_perm := char_perm);;
end;;

#############################################################################
##
##  ComputeLocalOuterGen( S_hat, P, Aut_S_hat, Inn_S_hat )
##
##  Computes the LOCAL outer information attached to the p-Sylow P:
##    - Aut_p := Stabilizer(Aut_S_hat, P)
##    - Inn_p := Aut_p intersection Inn_S_hat
##    - outer_order := |Aut_p / Inn_p| (must be 1 or 2)
##    - outer_gen := lift in Aut_p of a generator of the quotient
##                   (fail when outer_order = 1)
##
##  Returns rec(Aut_p, Inn_p, outer_order, outer_gen, outer_gen_order).
##
##  outer_gen_order = Order(outer_gen) (may be > 2; only outer_gen^2 in
##  Inn_p is guaranteed, so the action on Irr factors through C_2).
##
#############################################################################
ComputeLocalOuterGen := function(S_hat, P, Aut_S_hat, Inn_S_hat)
    local action, Aut_p, Inn_p, outer_order, nat, Q, gen_quotient,
          outer_gen, outer_gen_order;;

    action := function(sub, a) return Image(a, sub);; end;;

    ProgressMessage("Computing Stab_{Aut(S_hat)}(P).");;
    Aut_p := Stabilizer(Aut_S_hat, P, action);;

    ProgressMessage("Computing Aut_p intersection Inn(S_hat).");;
    Inn_p := Intersection(Aut_p, Inn_S_hat);;
    outer_order := Index(Aut_p, Inn_p);;

    if not outer_order in [1, 2] then
        Error(
            "Expected |Aut(S_hat)_p / Inn| in {1, 2}, but it is ",
            outer_order, "."
        );;
    fi;;

    if outer_order = 1 then
        outer_gen := fail;;
        outer_gen_order := 0;;
    else
        nat := NaturalHomomorphismByNormalSubgroup(Aut_p, Inn_p);;
        Q := Image(nat);;
        gen_quotient := First(Elements(Q), x -> x <> One(Q));;
        outer_gen := PreImagesRepresentative(nat, gen_quotient);;
        outer_gen_order := Order(outer_gen);;
    fi;;

    return rec(
        Aut_p := Aut_p,
        Inn_p := Inn_p,
        outer_order := outer_order,
        outer_gen := outer_gen,
        outer_gen_order := outer_gen_order
    );;
end;;

#############################################################################
##
##  ClassifyByGroup( G, p, outer_gen, t_Z, fus_Z )
##
##  Classifies Irr_{p'}(G) into types 1 and 2 via the outer action on
##  Irr(G).  outer_gen may be fail (every character is type 1).
##
##  Returns a record with the same fields as ClassifyByTables, plus
##  char_perm and class_perm (useful for diagnostics / verification).
##  via := "standard".
##
#############################################################################
ClassifyByGroup := function(G, p, outer_gen, t_Z, fus_Z)
    local table, irr, n, degrees, pprime_indices, case, partner, orbits,
          action, i, j, orb, central_lambda;;

    ProgressMessage("Building CharacterTable(G).");;
    table := CharacterTable(G);;
    irr := Irr(table);;
    n := Length(irr);;
    degrees := List(irr, chi -> chi[1]);;
    pprime_indices := Filtered([1 .. n], i -> degrees[i] mod p <> 0);;

    case := List([1 .. n], i -> 0);;
    partner := List([1 .. n], i -> fail);;
    orbits := [];;

    action := OuterActionOnIrr(G, table, outer_gen);;

    for i in pprime_indices do
        if case[i] <> 0 then
            continue;;
        fi;;
        j := i ^ action.char_perm;;

        if j = i then
            case[i] := 1;;
            Add(orbits, [i]);;
        else
            orb := Set([i, j]);;
            if Length(orb) <> 2 or
               orb[1] ^ action.char_perm <> orb[2] or
               orb[2] ^ action.char_perm <> orb[1] then
                Error("Orbit of size other than 1 or 2 on Irr_{p'}(G).");;
            fi;;
            case[orb[1]] := 2;;
            case[orb[2]] := 2;;
            partner[orb[1]] := orb[2];;
            partner[orb[2]] := orb[1];;
            Add(orbits, orb);;
        fi;;
    od;;

    central_lambda := CentralIndicesOfIrr(
        table, t_Z, fus_Z, pprime_indices
    );;

    return rec(
        via := "standard",
        table := table,
        irr := irr,
        degrees := degrees,
        pprime_indices := pprime_indices,
        case := case,
        partner := partner,
        orbits := orbits,
        central_lambda := central_lambda,
        t_Z := t_Z,
        fus_Z := fus_Z,
        base_group := G,
        char_perm := action.char_perm,
        class_perm := action.class_perm
    );;
end;;

#############################################################################
##
##  VerifyCliffordInGroup( G, A, emb_G_to_A, classification )
##
##  Verifies the classification (from ClassifyByGroup) by collecting
##  Clifford witnesses in A := G semidirect <outer_gen>.  For each psi in
##  Irr(A), restricts to Irr(G) via the class fusion.
##
##  For each p'-character classified:
##    - case 1: at least one witness of pattern (a) [irreducible restriction]
##    - case 2: the pair must share at least one witness of pattern (b)
##              [restriction = chi + chi^alpha]
##
##  If everything checks, returns rec(correct := true, ...).  Otherwise
##  raises Error with details.
##
#############################################################################
VerifyCliffordInGroup := function(G, A, emb_G_to_A, classification)
    local table_G, table_A, fus, irr_G, irr_A, restrictions,
          case1_witnesses, case2_witnesses, i, rest, desc, support,
          pos_i, common;;

    table_G := classification.table;;
    ProgressMessage("Building CharacterTable(A) for the Clifford check.");;
    table_A := CharacterTable(A);;

    ProgressMessage("Computing the class fusion G -> A.");;
    fus := FusionConjugacyClasses(emb_G_to_A, table_G, table_A);;
    if fus = fail then
        Error("Could not compute the class fusion G -> A.");;
    fi;;

    irr_G := Irr(table_G);;
    irr_A := Irr(table_A);;

    ProgressMessage("Restricting Irr(A) to Irr(G).");;
    restrictions := List(
        irr_A,
        psi -> ClassFunctionSameType(
            table_G, psi, ValuesOfClassFunction(psi){fus}
        )
    );;

    case1_witnesses := List([1 .. Length(irr_G)], i -> []);;
    case2_witnesses := List([1 .. Length(irr_G)], i -> []);;

    for i in [1 .. Length(restrictions)] do
        LoopProgress("Witness analysis", i, Length(restrictions));;
        rest := restrictions[i];;
        desc := MatScalarProducts(table_G, irr_G, [rest])[1];;
        support := Filtered([1 .. Length(irr_G)], j -> desc[j] <> 0);;

        # If Order(outer_gen) > 2, Irr(A) may contain restrictions with
        # patterns other than (a) / (b); we ignore them silently.
        if Length(support) = 1 and desc[support[1]] = 1 then
            Add(case1_witnesses[support[1]], i);;
        elif Length(support) = 2 and
             desc[support[1]] = 1 and desc[support[2]] = 1 then
            Add(case2_witnesses[support[1]], i);;
            Add(case2_witnesses[support[2]], i);;
        fi;;
    od;;

    for pos_i in [1 .. Length(classification.pprime_indices)] do
        i := classification.pprime_indices[pos_i];;
        if classification.case[i] = 1 then
            if Length(case1_witnesses[i]) = 0 then
                Error("No case-1 witness for chi[", i, "].");;
            elif Length(case2_witnesses[i]) <> 0 then
                Error(
                    "chi[", i, "] classified as case 1 ",
                    "but has a case-2 witness."
                );;
            fi;;
        else
            common := Intersection(
                case2_witnesses[i],
                case2_witnesses[classification.partner[i]]
            );;
            if Length(common) = 0 then
                Error(
                    "No shared case-2 witness for the pair (",
                    i, ", ", classification.partner[i], ")."
                );;
            elif Length(case1_witnesses[i]) <> 0 then
                Error(
                    "chi[", i, "] classified as case 2 ",
                    "but has a case-1 witness."
                );;
            fi;;
        fi;;
    od;;

    return rec(
        correct := true,
        table_A := table_A,
        fusion := fus,
        case1_witnesses := case1_witnesses,
        case2_witnesses := case2_witnesses
    );;
end;;
